name: Deploy Back Ventas

on:
  push:
    branches:
      - deploy
    paths:
      - 'back-Ventas_SpringBoot/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repo
        uses: actions/checkout@v4

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build imagen
        run: |
          docker build \
          -t ${{ secrets.DOCKER_USERNAME }}/back-ventas:latest \
          ./back-Ventas_SpringBoot

      - name: Push imagen
        run: |
          docker push \
          ${{ secrets.DOCKER_USERNAME }}/back-ventas:latest

      - name: Deploy EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_VENTAS_IP }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/back-ventas:latest

            docker stop back-ventas || true
            docker rm back-ventas || true

            docker run -d \
              --name back-ventas \
              -p 8080:8080 \
              ${{ secrets.DOCKER_USERNAME }}/back-ventas:latest

            docker image prune -f