name: Deploy Back Ventas

on:
  push:
    branches:
      - deploy
    paths:
      - 'back-Ventas_SpringBoot/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repo
        uses: actions/checkout@v4

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build imagen
        run: |
          docker build -t ${{ secrets.ECR_REPO_URL_VENTAS }}:latest ./back-Ventas_SpringBoot

      - name: Push imagen
        run: |
          docker push ${{ secrets.ECR_REPO_URL_VENTAS }}:latest

      - name: Deploy EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_VENTAS_IP }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          script: |
            sudo docker pull ${{ secrets.ECR_REPO_URL_VENTAS }}:latest

            sudo docker stop back-ventas || true
            sudo docker rm back-ventas || true

            sudo docker run -d \
              --name back-ventas \
              -p 8080:8080 \
              ${{ secrets.ECR_REPO_URL_VENTAS }}:latest

            sudo docker image prune -f